//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jango_Desktop.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplaySongBalloon {
            get {
                return ((bool)(this["DisplaySongBalloon"]));
            }
            set {
                this["DisplaySongBalloon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisplaySongBalloonAtEndOfSong {
            get {
                return ((bool)(this["DisplaySongBalloonAtEndOfSong"]));
            }
            set {
                this["DisplaySongBalloonAtEndOfSong"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JangoUsername {
            get {
                return ((string)(this["JangoUsername"]));
            }
            set {
                this["JangoUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JangoPassword {
            get {
                return ((string)(this["JangoPassword"]));
            }
            set {
                this["JangoPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoLogin {
            get {
                return ((bool)(this["AutoLogin"]));
            }
            set {
                this["AutoLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+Oemtilde")]
        public global::System.Windows.Forms.Keys KeyboardPlayPause {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyboardPlayPause"]));
            }
            set {
                this["KeyboardPlayPause"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+OemPeriod")]
        public global::System.Windows.Forms.Keys KeyboardNextTrack {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyboardNextTrack"]));
            }
            set {
                this["KeyboardNextTrack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+Up")]
        public global::System.Windows.Forms.Keys KeyboardRateUp {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyboardRateUp"]));
            }
            set {
                this["KeyboardRateUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+Down")]
        public global::System.Windows.Forms.Keys KeyboardRateDown {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyboardRateDown"]));
            }
            set {
                this["KeyboardRateDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+OemQuestion")]
        public global::System.Windows.Forms.Keys KeyboardDisplaySong {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyboardDisplaySong"]));
            }
            set {
                this["KeyboardDisplaySong"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplaySongRating {
            get {
                return ((bool)(this["DisplaySongRating"]));
            }
            set {
                this["DisplaySongRating"] = value;
            }
        }
    }
}
